name: Develop Workflow
on: 
  push:
    branches:
      - develop
      - main
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run security scan
        run: echo "Running security scan..."

  build:

    runs-on: ubuntu-latest
    environment: develop
    needs: [scan]

    steps:
        - name: Checkout
          uses: actions/checkout@v5

        - name: docker build
          run: |
              docker build -t my-app:latest .
        
        - name: docker login
          run: |
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

        - name: docker push
          run: |
            docker tag my-app:latest anikb29/monorepo-app/my-app:latest
            docker push anikb29/monorepo-app/my-app:latest
